DELETE FROM users_roles;
DELETE FROM comments;
DELETE FROM labels;
DELETE FROM tasks;
DELETE FROM projects;
DELETE FROM users;
DELETE FROM roles;

ALTER TABLE projects ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE roles ALTER COLUMN id RESTART WITH 1;
ALTER TABLE tasks ALTER COLUMN id RESTART WITH 1;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;
ALTER TABLE labels ALTER COLUMN id RESTART WITH 1;
